#ifndef CONFIG_H
#define CONFIG_H

#define POWERTRAIN_DATA_FRAME_ID 380
#define STEERING_SENSORS_FRAME_ID 342
#define CAR_SPEED_FRAME_ID 777
#define GEARBOX_FRAME_ID 419
#define SCM_FEEDBACK_FRAME_ID 660
#define TURN_SIGNAL_FRAME_ID SCM_FEEDBACK_FRAME_ID
#define CRUISE_BUTTONS_FRAME_ID	422
#define CRUISE_FRAME_ID	804
#define BRAKE_PRESSURE_FRAME_ID	420

#endif
